// Static daily rashifal content per sign (placeholder — will be AI/API driven later).
// Keyed by lowercase sign slug (matches zodiacSigns name.toLowerCase()).

export const rashifal = {
  aries: {
    overall: "Aaj aapki energy zabardast rahegi — koi ruka hua kaam aaj poora ho sakta hai. Apne aatmvishwas par bharosa rakhein.",
    love: "Partner ke saath din romantic rahega; singles ko kisi purane dost mein nayi feeling ho sakti hai.",
    career: "Kaam mein pehal karne se boss impress honge. Naye project ke liye achha din.",
    health: "Energy achhi, par gusse par control rakhein warna sar-dard ho sakta hai.",
    finance: "Achanak koi chhota financial gain mumkin. Bade kharche se bachein.",
    lucky: { number: 9, color: "Red", time: "Morning" },
    mood: "Confident",
    ratings: { love: 78, career: 85, health: 70 },
  },
  taurus: {
    overall: "Sthirta aur sabr aaj aapke sabse bade dost hain. Family ke saath waqt sukoon dega.",
    love: "Rishton mein garmahat badhegi; ek imandaar baat-cheet dil kareeb layegi.",
    career: "Mehnat ka phal milne ke aasaar; senior aapke kaam ki tareef karenge.",
    health: "Khaan-paan santulit rakhein; halki walk faydemand rahegi.",
    finance: "Investment ke liye achha samay, par soch-samajh kar.",
    lucky: { number: 6, color: "Green", time: "Evening" },
    mood: "Grounded",
    ratings: { love: 82, career: 72, health: 80 },
  },
  gemini: {
    overall: "Aapki baat-cheet aur ideas aaj logon ko impress karenge. Naye connections banenge.",
    love: "Flirty mood mein rahenge; partner ko surprise dena rishte ko taaza karega.",
    career: "Communication se koi deal ya interview aapke favour mein ja sakta hai.",
    health: "Mann thoda restless; meditation se shanti milegi.",
    finance: "Ek naya income source dikh sakta hai — dhyaan se dekhein.",
    lucky: { number: 5, color: "Yellow", time: "Afternoon" },
    mood: "Curious",
    ratings: { love: 74, career: 80, health: 68 },
  },
  cancer: {
    overall: "Bhaavnaayein aaj gehri rahengi. Apno ke saath samay aapko bhitar se mazboot karega.",
    love: "Emotional connection strong; ek pyaari yaad rishte ko sanjho degi.",
    career: "Intuition sahi rahegi — bade faisle mein apne mann ki sunein.",
    health: "Neend poori lein; paani zyada piyein.",
    finance: "Ghar ya property se juda koi achha samachar mil sakta hai.",
    lucky: { number: 2, color: "White", time: "Night" },
    mood: "Nurturing",
    ratings: { love: 85, career: 66, health: 74 },
  },
  leo: {
    overall: "Aaj aap centre of attention rahenge. Aapka charm har jagah kaam aayega.",
    love: "Romance apne peak par; grand gesture rishte mein jaan daal dega.",
    career: "Leadership dikhane ka mauka — moka haath se na jaane dein.",
    health: "Energy full, bas over-exertion se bachein.",
    finance: "Kharche par thoda control rakhein; dikhaawe se door rahein.",
    lucky: { number: 1, color: "Gold", time: "Midday" },
    mood: "Radiant",
    ratings: { love: 80, career: 88, health: 76 },
  },
  virgo: {
    overall: "Detail par dhyaan aaj aapko aage le jaayega. Planning ke liye behtareen din.",
    love: "Chhoti-chhoti caring baatein rishte ko mazboot karengi.",
    career: "Aapki organized approach se koi mushkil kaam aasaan ho jaayega.",
    health: "Digestion ka khyaal rakhein; simple bhojan behtar.",
    finance: "Budget banana faydemand; bachat badhegi.",
    lucky: { number: 5, color: "Sea Green", time: "Morning" },
    mood: "Focused",
    ratings: { love: 70, career: 84, health: 82 },
  },
  libra: {
    overall: "Santulan aur soundarya aaj aapke saath hain. Kisi jhagde ko pyaar se suljhaayenge.",
    love: "Rishton mein harmony; partner ke saath koi khaas plan banega.",
    career: "Team-work se success; diplomacy aapki taakat rahegi.",
    health: "Kamar/kidney ka khyaal; hydration zaroori.",
    finance: "Sahi mol-bhaav se ek achhi deal mil sakti hai.",
    lucky: { number: 6, color: "Pink", time: "Evening" },
    mood: "Balanced",
    ratings: { love: 83, career: 75, health: 71 },
  },
  scorpio: {
    overall: "Aapki gehri soch aaj chhupi hui sacchaai saamne laayegi. Intensity ko sahi disha dein.",
    love: "Passion strong; par jealousy se rishte ko bachaayein.",
    career: "Research ya investigation wale kaam mein aap chamkenge.",
    health: "Stress kam karein; deep breathing madad karegi.",
    finance: "Kisi purane paise ki wapsi mumkin hai.",
    lucky: { number: 9, color: "Maroon", time: "Night" },
    mood: "Intense",
    ratings: { love: 79, career: 82, health: 69 },
  },
  sagittarius: {
    overall: "Aaj adventure aur seekhne ka josh rahega. Naye rasté aapko inspire karenge.",
    love: "Rishton mein freedom aur maza; long-distance ke liye achha din.",
    career: "Naye opportunity ya travel se career ko boost mil sakta hai.",
    health: "Outdoor activity se energy badhegi; thighs ka khyaal.",
    finance: "Risky investment se abhi door rahein.",
    lucky: { number: 3, color: "Orange", time: "Afternoon" },
    mood: "Optimistic",
    ratings: { love: 76, career: 78, health: 84 },
  },
  capricorn: {
    overall: "Anushaasan aur mehnat aaj rang laayegi. Lambe samay ke lakshya paas aayenge.",
    love: "Serious rishton ke liye achha din; commitment gehra hoga.",
    career: "Boss/seniors aapki mehnat notice karenge — promotion ke yog.",
    health: "Ghutno/haddiyon ka khyaal; calcium lein.",
    finance: "Bachat aur planning se financial stability aayegi.",
    lucky: { number: 8, color: "Grey", time: "Morning" },
    mood: "Determined",
    ratings: { love: 68, career: 86, health: 77 },
  },
  aquarius: {
    overall: "Aapke unique ideas aaj sabse aage rahenge. Social circle mein aapki demand badhegi.",
    love: "Dosti pyaar mein badal sakti hai; mann ki baat kehne ka din.",
    career: "Innovation aur technology wale kaam mein safalta.",
    health: "Ankle/circulation ka khyaal; active rahein.",
    finance: "Group ya online se income ka naya zariya.",
    lucky: { number: 4, color: "Blue", time: "Evening" },
    mood: "Inventive",
    ratings: { love: 72, career: 81, health: 73 },
  },
  pisces: {
    overall: "Kalpana aur karuna aaj aapko khaas banaate hain. Kisi creative kaam mein mann lagega.",
    love: "Rishton mein romance aur gehraayi; ek pyaari surprise mil sakti hai.",
    career: "Creative aur helping fields mein aapki chamak dikhegi.",
    health: "Pair/immune system ka khyaal; rest zaroori.",
    finance: "Kharche par nazar rakhein; impulse buying se bachein.",
    lucky: { number: 7, color: "Purple", time: "Night" },
    mood: "Dreamy",
    ratings: { love: 84, career: 70, health: 72 },
  },
};

export function getRashifal(slug) {
  return rashifal[String(slug || "").toLowerCase()] || null;
}
